[package]
name = "amfm"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = {version = "0.29.0", features = ["unstable-rendered-line-info"]}
antenna = { path = "../antenna"}
clap = { version = "4.5.53", features = ["derive", "string"] }
dirs = "6.0.0"
tui-input = "0.14.0"
